http_server:
  addr: "localhost:8081"
  timeout: 4s
  idle_time: 6s
redis:
  addr: "localhost:6379"
  # password: ""
  "db": 0
postgres:
  host: "localhost" 
  user: "postgres"
  password: "test"
  db_name: "postgres"
  ssl_mode: "disable"
  port: 5432

# POSTGRES_PASSWORD
# POSTGRES_USER
# POSTGRES_DB
